name: routing_app
channels:
  - conda-forge
dependencies:
  - affine=2.4.0
  - anyio=4.0.0
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - arrow=1.2.3
  - asttokens=2.4.0
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - blosc=1.21.5
  - bokeh=3.2.2
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=4.3.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.1.1
  - cycler=0.11.0
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - fiona=1.9.4
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.7.2
  - geopandas=0.14.0
  - geopandas-base=0.14.0
  - georouting=0.0.8
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glpk=5.0
  - gmp=6.2.1
  - googlemaps=2.5.1
  - hdf4=4.2.15
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - json-c=0.17
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_console=6.6.3
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.9
  - kealib=1.5.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.0.6
  - libarchive=3.7.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.3.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.7.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.57.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libpq=15.4
  - libprotobuf=4.23.4
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - linkify-it-py=2.0.0
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markdown=3.4.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.0
  - minizip=4.0.1
  - mistune=3.0.1
  - munch=4.0.0
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.8.0
  - nbconvert-core=7.8.0
  - nbconvert-pandoc=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=7.0.4
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.92
  - numpy=1.26.0
  - openjpeg=2.5.0
  - openssl=3.1.3
  - osmnx=1.6.0
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.1
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - panel=1.2.3
  - param=1.13.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - polyline=2.0.0
  - poppler=23.08.0
  - poppler-data=0.4.12
  - postgresql=15.4
  - proj=9.3.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-igraph=0.10.8
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyviz_comms=3.0.0
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - rasterio=1.3.8
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.3
  - rtree=1.0.1
  - scikit-learn=1.3.1
  - scipy=1.11.2
  - send2trash=1.8.2
  - setuptools=68.2.2
  - shapely=2.0.1
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - snuggs=1.4.7
  - soupsieve=2.5
  - sqlite=3.43.0
  - stack_data=0.6.2
  - terminado=0.17.1
  - texttable=1.6.7
  - threadpoolctl=3.2.0
  - tiledb=2.16.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.10.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzcode=2023c
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - uri-template=1.3.0
  - urllib3=2.0.5
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.3
  - wheel=0.41.2
  - widgetsnbextension=4.0.9
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.7.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/routing_app
